Update mirror.yml

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -66,6 +66,12 @@ jobs:
             git push ${{ matrix.target_repo }} HEAD:refs/heads/${{ steps.target-branch.outputs.target_branch }}
             exit 0
           fi
+
+      - name: Remove mirror.yml from commit
+        run: |
+          git rm --cached mirror.yml || echo "mirror.yml was not found"
+          git commit -m "Remove mirror.yml from commit"
+
       - name: Merge histories
         run: |
           git fetch ${{ matrix.target_repo }} ${{ steps.target-branch.outputs.target_branch }}
